### ISSUE TITLE
dan-da/hd-wallet-addrs not found on packagist

### ISSUE THREAD

**Issue by oasin** [dan-da/hd-wallet-addrs#12]
dan-da/hd-wallet-addrs  not found on packagist?

**Comment by dan-da** [comment]
correct.  packagist is about libraries.   hd-wallet-addrs was written to be a command-line tool, not a library.

That said, the cli stuff is a thin wrapper around a big class that does most of the work, so it could be used by a 3rd party.   

Do you have a need for this functionality in code you are writing?

**Comment by oasin** [comment]
Yes i have a need for that in my project, i have Bitwasp bitcoin already installed, but i just want to get unused receiving address from an XPUB.

**Comment by dan-da** [comment]
hmm, I will see what I can do.

**Comment by oasin** [comment]
Okay, thanks am anticipating.

**Comment by dan-da** [comment]
I made a first cut at this.   See example usage:

https://github.com/dan-da/hd-wallet-addrs#embed-in-your-own-php-project

Right now it is still printing log info, but you can omit that by setting
```
$params['loglevel'] = 'fatalerror';
```

closing this.   If you find issues/problems, please open a new issue.
