### ISSUE TITLE
help me how to use a file containing xpub keys to check?

### ISSUE THREAD

**Issue by rehan43v3r** [dan-da/hd-wallet-addrs#13]
**i run this command :**
./hd-wallet-addrs.php -g --xpubfile=/mnt/c/Users/Rehan43v3r/Desktop/hd-wallet-addrs/xpub 
**_returned this error on a file which contains 6 xpubkeys_**  
![error xpub file](https://user-images.githubusercontent.com/59926080/74918360-f79ffa80-53ee-11ea-9e13-0b62e6392a1d.png)

when i used single xpub it worked well:
![single xpub okay](https://user-images.githubusercontent.com/59926080/74918752-92003e00-53ef-11ea-99b0-fce79623fbea.png)

Please help me how can i use multiple xpub keys which present in a file ...?

**Comment by dan-da** [comment]
multiple xpub keys are only supported for deriving multisig addresses.   If that's what you want, then you need to provide the --numsig argument to specify the number of required signers.    Eg, if you provide 3 xpub and --numsig=2, then that results in 2-of-3 multisig addresses.

If instead you just want to derive regular (non multisig) for multiple xpub keys, then you will need to run the program once for each key.

**Comment by rehan43v3r** [comment]
Hello Master dan-da i would like to contact you on discord.... please on any other social messengers you use .... Please reach me at discord: rehan43v3r#4865. I want to discuss you a about an amazing program creation. Please kindly reach me pleaseeee ....
