### ISSUE TITLE
./test_runner.php returning ERROR ... 

### ISSUE THREAD

**Issue by rehan43v3r** [dan-da/hd-wallet-addrs#14]
Developer tell me how to fix this error, when i tried to execute the test_runner.php this following error is coming up ...

![Error While running tests](https://user-images.githubusercontent.com/59926080/74947539-00a9bf80-5421-11ea-8045-642622b2c207.png)

**Comment by dan-da** [comment]
thanks for the report.   fixed in 5f3d2eb8e8341f0e4c3030872a938476330706f8
