### ISSUE TITLE
I need a program which can perform following actions ...

### ISSUE THREAD

**Issue by rehan43v3r** [dan-da/hd-wallet-addrs#15]
**Hello dan-da**, Your program is amazing and you are great developer.

I need your assistance in a program  which can perform following actions. **_50 percent of your program achieved this.. but remaining 50 percent needs to be implemented_** ... **The program should work in this way ....**

**"A Program or  bot CLi which can capable either to generate random bip32 passphrases OR capable to select one by one passphrase which is present in a .TXT format and generate XPRV and XPUB Values and save in temporary location and Check those Master XPUB for Any HD Wallets Which have actual balance in it? Either the balance may be 0 or Something Value then the program Must Print its XPUB and XPRV Keys ON SCREEN or to a Specific TXT format?"**

Your feedback and any further thoughts are greatly be appreciated ....

Thanks and Regards ....

Rehan43v3r
My Discord: rehan43v3r#4865
Please contact me at my discord or any other social messanger for further communication....

**Comment by RussianSwiss** [comment]
Stop bothering the creator.

**Comment by rehan43v3r** [comment]
@RussianSwiss, My intention is not to bother the creator ...
Where as My intention is to take this program to new level of coding ....

**Comment by dan-da** [comment]
@rehan43v3r for generating xpriv/xpub, you can use my other CLI program, [hd-wallet-derive](https://github.com/dan-da/hd-wallet-derive).  See the --gen-key option.

You can then take the ext_priv_key (or ext_pub_key) field (aka xpriv, xpub) and provide it as input to hd-wallet-addrs.  The hd-wallet-addrs report will tell you if there are any used addresses or not.   If I understand your business logic above, then you would display the xpriv (or xpub) to a file if the wallet has used addresses.

The above should be achievable with just a small glue script around hd-wallet-derive and hd-wallet-addrs.

that said, if I understand the intent correctly, it is to generate random new HD wallets and then check if they have ever received funds.  The odds of anyone ever finding such a wallet are so low that it is for all practical purposes guaranteed not to work.   Even if you could generate keys instantly and check if used in 1/1000th of a second, ti would not work.   But instead hd-wallet-addrs usually takes 5+ secs per xpub to lookup first 20 addrs on the blockchain.   So I don't like your chances of success.

anyway, good luck.

ps, I do not use discord, but if necessary, you can contact me directly: danda@osc.co.cr

**Comment by rehan43v3r** [comment]
@dan-da , Bravo developer please check your email inbox. Thanks for your quick communication.

**Comment by rehan43v3r** [comment]
Dear bravo developer danda……

Thank you very much for your quick reply...

Sorry for my delayed communication,  As I was busy, I did gave you quick reply …

I am rehan43v3r,  your GitHub follower! All your program(s) are awesome! I said I have been looking for a program which can capable to generate random XPRV and XPUB keys  and check those Master XPUB keys in  a series that whether they have ever actually been received funds!

In reply to my query, you said about your previous cli program hd-wallet-derive and also said that we need a 

                                                                a small glue script…

The script is now highly needed now … in order to perform bip32 on autopilot…..

All I need is now the glue script you said in our GitHub communication. Please kindly share me that script and instruction on how to use it  ….

I was inspired to this type of work … by one of my friends at cracked.to named ~Pruned

https://cracked.to/Thread-Leak-BruteFORCE-BITCOIN-BE-a-MILLIONAIRE-give-it-a-shut

Please check above URL you may find some interesting info. 

Thence from, I was started to generate bip32 XPRV’s and scanned then against any fund they have actually received in them!

I have done  a great time of spending on this system by generating lakhs of addresses using xprv keys and have been checked for any final balance in them? Awfully I did not succeed …....

I tried and tried in order to find btc final balance … when I almost lost my chance of finding btc…


I found your thread at GitHub hd-wallet-addrs Which was really an amazing program which helped me to use which XPUB has actually got received balance! If any final balance is found then I can able to spent those funds …

I used this way to get XPRV and Xpubs …

Using a  BIP32 Passphrase (WEAKER) and generating XPRV and XPUB at bip32.org and 
Checking the XPUB whether it actually got received any funds or not ….

I used Pruned program by generating Private Keys for Corresponding XPUBs …..

Dear Danda ….

All I need is now, establish a bridge between these two program which work on single command 
You said it was a GLUE SCRIPT …

Please communicate with me further for future communication or reach me at my discord 
Rehan43v3r#4865.

Hope I will find something with your help …, If it is done so, I fund your wallet too …..

Thanks and regards…..
Rehan43v3r
Discord: rehan43v3r#4865

**Comment by rehan43v3r** [comment]
@dan-da, waiting for your reply ..... Please answer....

**Comment by EAWF** [comment]
Rehan,
Since you either have not completely thought out your request, or you have relatively low moral and ethical standards along with a questionable upbringing, you'd probably be better off using this [BIP39 Generator](https://iancoleman.io/bip39/) to generate random master keys and payment addresses, and then run each of the payment addresses one by one through a blockchain explorer of your choice to see if there's any bitcoin there that you might be able to steal from someone.

**Comment by rehan43v3r** [comment]
@EAWF, Thanks for your reply .... i know about how iancoleman.io works .... The problem is here to check those each and every wallet address for balance is very time consuming.... 
I need a program which can do all this job on autopilot! 

Presently @dan-da, is not replying to any of the queries. 

We first come to know which XPUB has final balance... Then using iancoleman.io we use our XPRV to spent those funds. Here HD Wallet Address is very strong program to find whether the XPUB HD Wallets have been with Final Balance or not!

Thanks for all in this thread participation...

**Comment by EAWF** [comment]
No, you do not NEED a program, you WANT a program that will allow you to steal money which does not belong to you, in other words, you are potentially a thief.
You are also asking, in a public forum, for someone to aid and abet you in that theft and open them to prosecution and jail time. What a nice person you are! NOT. Don't bother responding. I have already blocked you as a loser.
