### ISSUE TITLE
PHP Error?

### ISSUE THREAD

**Issue by Sir-Lagsalot** [dan-da/hd-wallet-addrs#2]
Sorry, i'm not a PHP pro.

When I try running your code on my online IDE (c9.io), I get an error. How would I fix it?

> PHP Warning:  Uncaught exception 'ErrorException' with message 'require_once(/home/ubuntu/workspace/lib/../vendor/autoload.php): failed to open stream: No such file or directory' in /home/ubuntu/workspace/lib/walletaddrs.class.php:3
> Stack trace:
> #0 /home/ubuntu/workspace/lib/walletaddrs.class.php(3): _global_error_handler(2, 'require_once(/h...', '/home/ubuntu/wo...', 3, Array)
> #1 /home/ubuntu/workspace/lib/walletaddrs.class.php(3): require_once()
> #2 /home/ubuntu/workspace/hd-wallet-addrs.php(14): require_once('/home/ubuntu/wo...')
> #3 {main}
>   thrown in /home/ubuntu/workspace/lib/walletaddrs.class.php on line 3
> 
> Warning: Uncaught exception 'ErrorException' with message 'require_once(/home/ubuntu/workspace/lib/../vendor/autoload.php): failed to open stream: No such file or directory' in /home/ubuntu/workspace/lib/walletaddrs.class.php:3
> Stack trace:
> #0 /home/ubuntu/workspace/lib/walletaddrs.class.php(3): _global_error_handler(2, 'require_once(/h...', '/home/ubuntu/wo...', 3, Array)
> #1 /home/ubuntu/workspace/lib/walletaddrs.class.php(3): require_once()
> #2 /home/ubuntu/workspace/hd-wallet-addrs.php(14): require_once('/home/ubuntu/wo...')
> #3 {main}
>   thrown in /home/ubuntu/workspace/lib/walletaddrs.class.php on line 3
> PHP Fatal error:  main(): Failed opening required '/home/ubuntu/workspace/lib/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/ubuntu/workspace/lib/walletaddrs.class.php on line 3
> 
> Fatal error: main(): Failed opening required '/home/ubuntu/workspace/lib/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/ubuntu/workspace/lib/walletaddrs.class.php on line 3
> Ouch! Encountered PHP Fatal Error.  Shutting down.
> Array
> (
>     [type] => 64
>     [message] => main(): Failed opening required '/home/ubuntu/workspace/lib/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear')
>     [file] => /home/ubuntu/workspace/lib/walletaddrs.class.php
>     [line] => 3
> )
> WARNING: ALERTS_MAIL_TO not defined in config.  alert not sent with subject: [weeabear-bitcoin-project-3664415] [hd-wallet-addrs.php] PHP Fatal Error! [pid: 12580]

**Comment by dan-da** [comment]
There is a dependency on bitwasp/bitcoin.   You need to run composer to install it first.

```
 php -r "readfile('https://getcomposer.org/installer');" | php
 php composer.phar install
```

after that it should work.

**Comment by Sir-Lagsalot** [comment]
Fixed. Apt-get wasnt updated, and in turn would not install php5-gmt.

**Comment by Sir-Lagsalot** [comment]
This made composer not install anything.

**Comment by dan-da** [comment]
ah, ok.  That's a new one on me.   Seems like composer should've complained about any errors, but who knows.   I'm glad you resolved it.
