### ISSUE TITLE
How to use secp256k1?

### ISSUE THREAD

**Issue by Sir-Lagsalot** [dan-da/hd-wallet-addrs#3]
Hey, I love your program, however I have to agree, it's very slow. You say in the installation notes that using [this extension](https://github.com/Bit-Wasp/secp256k1-php) will speed it up greatly. I've installed it using the installation instruction given in that readme. I don't feel see any difference in processing times. Is there any thing more I need to do?

**Comment by dan-da** [comment]
make sure the extension is being loaded.    eg:

$ php -r "phpinfo();" | grep secp256k1
```
/etc/php5/cli/conf.d/20-secp256k1.ini,
secp256k1
secp256k1 support => enabled
```

If not, check your php config, eg:

$ cat /etc/php5/cli/conf.d/20-secp256k1.ini 
```
; configuration for php GMP module
; priority=20
extension=secp256k1.so
```

**Comment by Sir-Lagsalot** [comment]
I went into root and cannot find the secp256k1.so file in my php5 file. When I try to install it, I get this error: 

https://github.com/Bit-Wasp/secp256k1-php/issues/53

**Comment by dan-da** [comment]
It seems that PHP 5.x is no longer supported in the latest release(s) of that extension.    I was able to get it to work by:

```
$ cd secp256k1-php/secp256k1
git checkout v0.0.7
phpize5 && ./configure --with-secp256k1 && make && sudo make install
```

note: might need to use phpize instead of phpize5 on your system.

note: v.0.0.8 did NOT work even though readme indicates that all 0.0.* should work with php5.x.

**Comment by Sir-Lagsalot** [comment]
Now I don't get a problem when installing the php lib, thanks.

But when I try checking my php files, as you suggested above, I get this.

weeabear:~/workspace/Storage/hd-wallet-addrs/secp256k1 (master) $ php -r "phpinfo();" | grep secp256k1
PWD => /home/ubuntu/workspace/Storage/hd-wallet-addrs/secp256k1
_SERVER["PWD"] => /home/ubuntu/workspace/Storage/hd-wallet-addrs/secp256k1
_ENV["PWD"] => /home/ubuntu/workspace/Storage/hd-wallet-addrs/secp256k1
weeabear:~/workspace/Storage/hd-wallet-addrs/secp256k1 (master) $ cat /etc/php5/cli/conf.d/20-secp256k1.ini
cat: /etc/php5/cli/conf.d/20-secp256k1.ini: No such file or directory

**Comment by dan-da** [comment]
try creating that file.  with the same contents as I posted above.

**Comment by dan-da** [comment]
I added PHP5 build instructions to the readme.   closing this.
