### ISSUE TITLE
Class 'MdanterEccMathGmp' not found

### ISSUE THREAD

**Issue by ByteFan** [dan-da/hd-wallet-addrs#4]
Hi there,
Just freshly installed on ubuntu+php7. I have the following error when running from the command line:

php ./hd-wallet-addrs.php -g --xpub=xpub6BfKpqjTwvH21wJGWEfxLppb8sU7C6FJge2kWb9315oP4ZVqCXG29cdUtkyu7YQhHyfA5nt63nzcNZHYmqXYHDxYo8mm1Xq1dAC7YtodwUR --gen-only=1 --api=blockchaindotinfo

PHP Fatal error:  Class 'Mdanter\Ecc\Math\Gmp' not found in /hd-wallet-addrs/vendor/bitwasp/bitcoin/src/Math/Math.php on line 8
Ouch! Encountered PHP Fatal Error.  Shutting down.
Array
(
    [type] => 1
    [message] => Class 'Mdanter\Ecc\Math\Gmp' not found
    [file] => /hd-wallet-addrs/vendor/bitwasp/bitcoin/src/Math/Math.php
    [line] => 8
)

I have:
ls -al vendor/mdanter/ecc/
total 56
drwxr-xr-x 6 webadmin webadmin 4096 May 23 10:45 .
drwxr-xr-x 3 webadmin webadmin 4096 May 23 10:45 ..
-rw-r--r-- 1 webadmin webadmin 1173 Jan  4 13:13 composer.json
drwxr-xr-x 2 webadmin webadmin 4096 Jan  4 13:13 doc
drwxr-xr-x 2 webadmin webadmin 4096 Jan  4 13:13 examples
-rwxr-xr-x 1 webadmin webadmin   36 Jan  4 13:13 .gitignore
-rw-r--r-- 1 webadmin webadmin  897 Jan  4 13:13 Makefile
-rwxr-xr-x 1 webadmin webadmin  943 Jan  4 13:13 phpunit.xml
-rw-r--r-- 1 webadmin webadmin 7713 Jan  4 13:13 README.md
-rw-r--r-- 1 webadmin webadmin  636 Jan  4 13:13 .scrutinizer.yml
drwxr-xr-x 9 webadmin webadmin 4096 Jan  4 13:13 src
drwxr-xr-x 5 webadmin webadmin 4096 Jan  4 13:13 tests
-rw-r--r-- 1 webadmin webadmin  663 Jan  4 13:13 .travis.yml

Please help thx.

**Comment by dan-da** [comment]
Thanks for the report.  If you cloned from git, do a git pull, then "composer update".  After that it should work.

Otherwise, you can manually make the change.

Edit composer.json and edit the bitwasp line to:

    "bitwasp/bitcoin": ">=0.0.19",

then run "composer update".

After that, it should work.

Please reply with your results.

**Comment by ByteFan** [comment]
Works nice! Thank you very much.
